#!/bin/bash
#SBATCH -n 4                 
#SBATCH -N 1                 
#SBATCH -D /tmp              
#SBATCH -t 2-00:00           
#SBATCH -p dcca40               # Usar la cola TFG
#SBATCH --mem 8192           
#SBATCH --gres gpu:1         
#SBATCH -o standup_%u_%j.out  
#SBATCH -e standup_%u_%j.err  

# Activar el entorno virtual
conda activate nerfstudio
# Ejecutar el comando de entrenamiento de NeRFStudio

ns-render camera-path --load-config /hhome/aceballosa/NeRF-Gaussian-Splatting/outputs/standup/nerf/standup/nerfacto/2025-04-07_174956/config.yml --camera-path-filename /hhome/aceballosa/NeRF-Gaussian-Splatting/datasets/dnerf/standup/camera_paths/2025-04-07-17-50-05.json --output-path renders/standup/2025-04-07-17-50-05.mp4

conda deactivate