#!/bin/bash
#SBATCH -n 4                 
#SBATCH -N 1                 
#SBATCH -D /tmp              
#SBATCH -t 2-00:00           
#SBATCH -p dcca40               # Usar la cola TFG
#SBATCH --mem 8192           
#SBATCH --gres gpu:1         
#SBATCH -o standup_%u_%j.out  
#SBATCH -e standup_%u_%j.err  
 

# Activar el entorno virtual
conda activate nerfstudio

# Ejecutar el comando de entrenamiento de NeRFStudio
ns-export pointcloud --load-config /hhome/aceballosa/NeRF-Gaussian-Splatting/outputs/standup/nerf/standup/nerfacto/2025-04-07_174956/config.yml --output-dir /hhome/aceballosa/NeRF-Gaussian-Splatting/exports/standup/pcd --num-points 1000000 --remove-outliers True --normal-method open3d --save-world-frame False
ns-export poisson --load-config /hhome/aceballosa/NeRF-Gaussian-Splatting/outputs/standup/nerf/standup/nerfacto/2025-04-07_174956/config.yml --output-dir /hhome/aceballosa/NeRF-Gaussian-Splatting/exports/standup/poisson --target-num-faces 50000 --num-pixels-per-side 2048 --num-points 1000000 --remove-outliers True --normal-method open3d 

conda deactivate