#!/bin/bash
#SBATCH -n 4                 
#SBATCH -N 1                 
#SBATCH -D /tmp              
#SBATCH -t 2-00:00           
#SBATCH -p tfg               # Usar la cola TFG
#SBATCH --mem 8192           
#SBATCH --gres gpu:1         
#SBATCH -o trex_%u_%j.out  
#SBATCH -e trex_%u_%j.err  

# Activar el entorno virtual
source /fhome/aceballos/venvs/nerfstudio/bin/activate

# Ejecutar el comando de entrenamiento de NeRFStudio
ns-render camera-path --load-config outputs/test_01/nerfacto/2025-03-24_182935/config.yml --camera-path-filename /fhome/aceballos/tfg/NeRF-Gaussian-Splatting/datasets/test_01/camera_paths/2025-03-24-18-29-48.json --output-path renders/test_01/2025-03-24-18-29-48.mp4
# Desactivar el entorno virtual
deactivate