#!/bin/bash
#SBATCH -n 4                 
#SBATCH -N 1                 
#SBATCH -D /tmp              
#SBATCH -t 2-00:00           
#SBATCH -p tfg               # Usar la cola TFG
#SBATCH --mem 8192           
#SBATCH --gres gpu:1         
#SBATCH -o trex_%u_%j.out  
#SBATCH -e trex_%u_%j.err  

# Activar el entorno virtual
source /fhome/aceballos/venvs/nerfstudio/bin/activate

# Ejecutar el comando de entrenamiento de NeRFStudio
ns-render tsdf --load-config /hhome/aceballosa/NeRF-Gaussian-Splatting/outputs/lego/nerf/lego/nerfacto/2025-04-04_200704/config.yml --output-dir /export/hhome/aceballosa/NeRF-Gaussian-Splatting/exports/lego/pcd 
# Desactivar el entorno virtua
deactivate