#!/bin/bash
#SBATCH -n 4
#SBATCH -N 1
#SBATCH -D /tmp
#SBATCH -t 2-00:00
#SBATCH -p dcca40
#SBATCH --mem 8192
#SBATCH --gres gpu:1
#SBATCH -o train_%u_%j.out
#SBATCH -e train_%u_%j.err

conda activate nerfstudio

# Entrenamiento
ns-train vanilla-nerf --data /hhome/aceballosa/NeRF-Gaussian-Splatting/datasets/dnerf/trex --output-dir /hhome/aceballosa/NeRF-Gaussian-Splatting/outputs/train_06 dnerf-data 

conda deactivate
